repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
- name: ingress
  namespace: gitlab-managed-apps
  chart: stable/nginx-ingress
  version: 1.40.2
  installed: false  # disabling while I'm not sure how to configure this correctly for Fargate (see values file)
  values:
    - values.yaml
