controller:
  image:
    repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
    allowPrivilegeEscalation: false
  stats:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

  # extraArgs:
  #   http-port: 8080
  #   https-port: 8443

  # containerPort:
  #   http: 8080
  #   https: 8443

  # service:
  #   ports:
  #     http: 80
  #     https: 443
  #   targetPorts:
  #     http: 8080
  #     https: 8443
  #   annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
  #     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

