apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiName | required "apiName required" }}
  namespace: {{ .Release.Namespace | required "namespace required" }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4}}
  labels:
    app: {{ .Values.apiName | required "apiName required" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.apiName | required "apiName required" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
