apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celeryWorkerName | required "celeryWorkerName required" }}
  namespace: {{ .Release.Namespace | required "namespace required" }}
  labels:
    app: {{ .Values.celeryWorkerName | required "celeryWorkerName required" }}
  creationTimestamp: null
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ .Values.celeryWorkerName | required "celeryWorkerName required" }}
  template:
    metadata:
      labels:
        name: {{ .Values.celeryWorkerName | required "celeryWorkerName required" }}
      creationTimestamp: null
    spec:
      containers:
        - name: {{ .Values.image.name | required "image name required" }}
          image: "{{ .Values.image.backendRepository }}:{{ .Values.image.tag }}"
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          command:
            - "bash"
            - "-c"
            - "celery -A app.worker worker -l info -Q ytta-celery"
